### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by jizongFox** [kulikovv/harmonic#1]
Dear authors,
Thanks for the wonderful work and the release of the code. I am playing with the code and am interested in the dataset of CVPPP2017 plant leaf instance segmentation. I noticed that the data has no longer been available. Have you had any suggestions on how to get one of the four datasets you used in the paper?
Your comments would be greatly appreciated.

**Comment by kulikovv** [comment]
Thank you for your interest in our work,
CVPPP 2017 can be found by this [link](https://competitions.codalab.org/competitions/18405)
Please find the cell datasets by this [link ](http://celltrackingchallenge.net/2d-datasets/)
To get the dataset you need to register in the challenges.
Hope that help.
